# Generated by Django 6.0.6 on 2026-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('regular_user', 'Regular User'), ('admin', 'Admin')], default='regular_user', max_length=20),
        ),
    ]
