# Generated by Django 6.0.6 on 2026-08-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(db_index=True, help_text='Opaque client-generated fingerprint that identifies this device.', max_length=512, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Most-recent IP address seen for this guest.')),
                ('trial_started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guest Session',
                'verbose_name_plural': 'Guest Sessions',
                'ordering': ['-trial_started_at'],
            },
        ),
    ]
