# Generated by Django 6.0.6 on 2026-08-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_guest_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='has_tried_2d_view',
            field=models.BooleanField(default=False, help_text='Whether the guest has tried the 2D view feature.'),
        ),
        migrations.AddField(
            model_name='guestsession',
            name='has_tried_ar_view',
            field=models.BooleanField(default=False, help_text='Whether the guest has tried the AR view feature.'),
        ),
    ]
