# Generated by Django 6.0.6 on 2026-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_guestsession_has_tried_2d_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='date_of_usage',
            field=models.DateField(auto_now_add=True, help_text='The date this guest session was created and is valid for.', null=True),
        ),
    ]
