# Generated by Django 6.0.6 on 2026-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_guestsession_date_of_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestsession',
            name='date_of_usage',
        ),
        migrations.AlterField(
            model_name='guestsession',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='The exact datetime the trial started (when the 2D view was first accessed).', null=True),
        ),
    ]
