# Generated by Django 6.0.6 on 2026-06-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_category_created_by_comment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='mappedin_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
