# Generated by Django 6.0.6 on 2026-06-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_venue_mappedin_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='mappedin_key',
            new_name='mappedin_map_id',
        ),
    ]
