# Generated by Django 6.0.3 on 2026-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_locationconversation_locationmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
