from forum.routing import websocket_urlpatterns as forum_websocket_urlpatterns
from notifications.routing import websocket_urlpatterns as notifications_websocket_urlpatterns

websocket_urlpatterns = forum_websocket_urlpatterns + notifications_websocket_urlpatterns
