# Generated by Django 6.0.6 on 2026-06-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('comment', 'Comment'), ('upvote', 'Upvote'), ('moderation', 'Moderation'), ('broadcast', 'Broadcast')], max_length=20),
        ),
    ]
